### PR TITLE
(feat) Add short number system

### PR DESCRIPTION
**Pull request by ahqsoftwares**
# What does this PR aim to do
This PR introduces the following
- ShortEnd Properties for xp
- Supports upto "Q" [Quadrillions]

# Type
- Feature
- Minor Feature

# Requires
- Minor Version

### CODE REVIEW

**Comment by ahqsoftwares** [comment]
@iAsure

**Comment by iAsure** [comment]
Hi! Sorry for the delay, I find it an interesting feature and I would like to implement it, only the other formatting changes I would avoid for now

**Comment by ahqsoftwares** [comment]
> Hi! Sorry for the delay, I find it an interesting feature and I would like to implement it, only the other formatting changes I would avoid for now

I see

**Pull request closed without merging**
