### PR TITLE
Badge Frame Fix

### LINKED ISSUE #8: I found some issues with the badge frame
I noticed that a 'badge frame' is not always created or it is created with excessive width. I attached a Screenshot at the end of this issue.

Here is the code snippet:

```
const buffer = await profileImage(member.id, {
        badgesFrame: true,
    });

    const attachment = new AttachmentBuilder(buffer, { name: 'welcome.png' });
```

If there is any way I can assist further, please let me know.

My Discord username is .jermayn, and I can always be reached there.

image

### PR DESCRIPTION
**Pull request by Voroniyx**
This commit fixes a bug found in [#8](https://github.com/iAsure/discord-arts/issues/8). It also adds support for the Auto Mode Rule Create badge. @JermaynCodes this should Closes #8 . @iAsure maybe you could look at the changes and then merge them together

### CODE REVIEW

**Comment by Voroniyx** [comment]
And maybe who can get a better car mod rule create badge. My PNG converter somehow made it very pixelated

**Comment by JermaynCodes** [comment]
Hey, for any reasy this bot  https://japi.rest/discord/v1/user/672822334641537041 has some kind of an invisible Badge called "BOT_HTTP_INTERACTIONS". If you add add the following then everything should be nice with the badge borders.

I attached 2 Images one is without my few changes and one with my changes.

let public_flags_array = data.public_flags_array.filter((value) => value !== "BOT_HTTP_INTERACTIONS");
```
  let badgesLength =
  (options?.overwriteBadges && options?.customBadges?.length
    ? 0
    : public_flags_array.length) +
  (options?.customBadges?.length ? options?.customBadges?.length : 0);
  ```
  
  before
after

**Comment by Voroniyx** [comment]
hey, i already did something similar in line 171. i think i do the same or something similar. but thank you for the note

**Comment by JermaynCodes** [comment]
Alright, should I delete my comment to prevent confusion?

**Comment by Voroniyx** [comment]
no not necessary

**Comment by iAsure** [comment]
Thank you so much for noticing this!

**Comment by Voroniyx** [comment]
@iAsure would you merge this pr? Or do you waiting for something.

**Comment by iAsure** [comment]
> @iAsure would you merge this pr? Or do you waiting for something.

I initiated a review, as there are several lines of console.log in the PR 😅

**Comment by Voroniyx** [comment]
> > @iAsure would you merge this pr? Or do you waiting for something.
> 
> @Voroniyx I initiated a review, as there are several lines of console.log in the PR 😅
@iAsure oh no, I totally forgot, should be removed now

**Comment by iAsure** [comment]
Thanks! For now I will not publish it in NPM as I am working on another update, but I will combine everything as soon as it is ready

**Pull request merged**
